server:
  port: 8761
  servlet:
    context-path: /registry

spring:
  application:
    name: registry

eureka:
  client:
    register-with-eureka: false
    fecth-register: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka